using MediatR;
using Ship24X7.Payment.Application.DTOs;

namespace Ship24X7.Payment.Application.Commands;

/// <summary>
/// Command for creating a new payment order in Razorpay payment gateway.
/// Encapsulates all required data for payment order creation including shipment details, amount, and idempotency.
/// Implements IRequest pattern from MediatR for CQRS architecture.
/// Returns PaymentOrderResponse containing Razorpay order ID and key for frontend payment integration.
/// Used by frontend after shipment creation to initiate payment flow.
/// Idempotency key ensures duplicate requests return the same payment order without creating multiple orders.
/// </summary>
public class CreatePaymentOrderCommand : IRequest<PaymentOrderResponse>
{
    /// <summary>
    /// Gets or sets the unique identifier of the shipment for which payment is being collected.
    /// Links payment order to specific shipment for tracking and fulfillment.
    /// Required field. Must be a valid shipment ID from the shipment service.
    /// </summary>
    public Guid ShipmentId { get; set; }

    /// <summary>
    /// Gets or sets the tracking number of the shipment.
    /// Used in Razorpay receipt for easy identification and reconciliation.
    /// Format: SHIP_{TrackingNumber} in Razorpay order.
    /// Required field. Example: "SHIP123456789"
    /// </summary>
    public string TrackingNumber { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the payment amount in the specified currency.
    /// Represents the total cost of the shipment including all charges.
    /// Must be positive and greater than zero.
    /// Converted to smallest currency unit (paise for INR) when sent to Razorpay.
    /// Example: 500.00 for ₹500
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Gets or sets the currency code for the payment.
    /// Defaults to "INR" (Indian Rupees).
    /// Must be a valid ISO 4217 currency code supported by Razorpay.
    /// Examples: "INR", "USD", "EUR"
    /// </summary>
    public string Currency { get; set; } = "INR";

    /// <summary>
    /// Gets or sets the idempotency key to prevent duplicate payment order creation.
    /// If a payment order with this key already exists, the existing order is returned instead of creating a new one.
    /// Should be unique per payment request, typically generated by the client.
    /// Required field. Example: "ship_123456789_1234567890"
    /// </summary>
    public string IdempotencyKey { get; set; } = string.Empty;
}
