using MediatR;

namespace Ship24X7.Payment.Application.Commands;

/// <summary>
/// Command for verifying payment signature after successful payment on Razorpay frontend.
/// Encapsulates Razorpay payment verification data including order ID, payment ID, and signature.
/// Implements IRequest pattern from MediatR for CQRS architecture.
/// Returns boolean indicating whether payment signature is valid and payment was successfully verified.
/// Critical security step: Validates HMAC-SHA256 signature to ensure payment authenticity and prevent tampering.
/// Used by frontend after user completes payment on Razorpay checkout to confirm payment legitimacy.
/// </summary>
public class VerifyPaymentCommand : IRequest<bool>
{
    /// <summary>
    /// Gets or sets the Razorpay order ID that was created during payment order creation.
    /// Links the payment to the original order in Ship24X7 system.
    /// Used in signature validation formula: razorpay_order_id|razorpay_payment_id
    /// Required field. Example: "order_ABC123XYZ456"
    /// </summary>
    public string RazorpayOrderId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Razorpay payment ID generated after successful payment.
    /// Unique identifier for the payment transaction in Razorpay system.
    /// Used in signature validation formula: razorpay_order_id|razorpay_payment_id
    /// Stored in payment order for future reference and refund operations.
    /// Required field. Example: "pay_XYZ789ABC123"
    /// </summary>
    public string RazorpayPaymentId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Razorpay signature generated by Razorpay after payment completion.
    /// HMAC-SHA256 hash of "razorpay_order_id|razorpay_payment_id" using Razorpay key secret.
    /// Handler validates this signature to ensure payment was actually processed by Razorpay.
    /// Prevents fraudulent payment confirmations and ensures data integrity.
    /// Required field. Example: "a1b2c3d4e5f6..."
    /// </summary>
    public string RazorpaySignature { get; set; } = string.Empty;
}
