using MediatR;
using Ship24X7.Auth.Application.DTOs;

namespace Ship24X7.Auth.Application.Commands;

/// <summary>
/// Command for authenticating a user and issuing JWT access and refresh tokens.
/// Encapsulates login credentials including email, password, and optional MFA code.
/// Implements IRequest pattern from MediatR for CQRS architecture.
/// Returns LoginResponse containing access token, refresh token, expiration, and MFA requirement flag.
/// Supports standard email/password authentication with optional multi-factor authentication (MFA).
/// Implements account security features: password verification, account locking after failed attempts, email verification check.
/// Refresh token stored in HttpOnly cookie by controller for security.
/// </summary>
public class LoginCommand : IRequest<LoginResponse>
{
    /// <summary>
    /// Gets or sets the user's email address for authentication.
    /// Used to identify the user account in the database.
    /// Must match the email used during registration.
    /// Case-insensitive comparison for user convenience.
    /// Required field. Example: "customer@example.com"
    /// </summary>
    public string Email { get; set; } = string.Empty;
    
    /// <summary>
    /// Gets or sets the user's password for authentication.
    /// Compared against stored BCrypt hash for verification.
    /// Failed password attempts increment counter and may lock account after 5 failures.
    /// Required field. Example: "SecureP@ss123"
    /// </summary>
    public string Password { get; set; } = string.Empty;
    
    /// <summary>
    /// Gets or sets the optional MFA code for multi-factor authentication.
    /// Required only when user has MFA enabled on their account.
    /// 6-digit TOTP code generated by authenticator app (Google Authenticator, Authy, etc.).
    /// Validated using TOTP algorithm with ±1 time step window (90 seconds total).
    /// If MFA enabled and code not provided, handler returns RequiresMfa=true flag.
    /// Optional field. Example: "123456"
    /// </summary>
    public string? MfaCode { get; set; }
}
