using MediatR;

namespace Ship24X7.Auth.Application.Commands;

/// <summary>
/// Command for verifying a multi-factor authentication (MFA) code during MFA setup or login.
/// Encapsulates user ID and 6-digit TOTP code for validation.
/// Implements IRequest pattern from MediatR for CQRS architecture.
/// Returns boolean indicating successful verification (true) or failure (false).
/// Validates TOTP code using HMAC-SHA1 algorithm with user's secret key and current timestamp.
/// Allows time window of ±1 step (90 seconds total) to account for clock drift.
/// If verification succeeds during setup, enables MFA for user account (IsEnabled=true).
/// If verification fails, increments failed attempts counter and may lock MFA temporarily.
/// </summary>
public class VerifyMfaCommand : IRequest<bool>
{
    /// <summary>
    /// Gets or sets the unique identifier of the user verifying MFA.
    /// Extracted from JWT token claims by controller or provided during login.
    /// Used to retrieve user's MFA settings and secret key for validation.
    /// Required field. Example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
    /// </summary>
    public Guid UserId { get; set; }
    
    /// <summary>
    /// Gets or sets the time-based one-time password (TOTP) code to verify.
    /// 6-digit code generated by authenticator app (Google Authenticator, Authy, etc.).
    /// Code changes every 30 seconds based on TOTP algorithm.
    /// Handler validates code using HMAC-SHA1(secret, time_step) where time_step = floor(current_time / 30).
    /// Validation allows ±1 time step window (90 seconds total) for clock synchronization.
    /// Required field. Example: "123456"
    /// </summary>
    public string Code { get; set; } = string.Empty;
}
