using Ship24X7.Shared.Domain;

namespace Ship24X7.Payment.Domain.Entities;

/// <summary>
/// Domain entity representing a payment refund in the Ship24X7 payment system.
/// Encapsulates refund data, business rules, and relationships with payment orders and Razorpay.
/// Inherits from BaseEntity for common audit fields (CreatedAt, CreatedBy, UpdatedAt, UpdatedBy, CorrelationId).
/// Tracks refund lifecycle from initiation (Initiated) through processing (Processed) or failure (Failed).
/// Links to parent payment order and Razorpay refund for refund tracking and reconciliation.
/// Supports partial and full refunds for captured payments.
/// </summary>
public class PaymentRefund : BaseEntity
{
    /// <summary>
    /// Gets or sets the unique identifier for the payment refund.
    /// Primary key in the database.
    /// Used for internal references and API responses.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the unique identifier of the payment order being refunded.
    /// Foreign key linking refund to parent payment order.
    /// Payment order must be in Captured status to initiate refund.
    /// Required field. Must be a valid payment order ID.
    /// </summary>
    public Guid PaymentOrderId { get; set; }

    /// <summary>
    /// Gets or sets the Razorpay refund ID generated by Razorpay when refund is initiated.
    /// Unique identifier for the refund in Razorpay system.
    /// Used for refund tracking and webhook processing.
    /// Nullable. Example: "rfnd_ABC123XYZ456"
    /// </summary>
    public string? RazorpayRefundId { get; set; }

    /// <summary>
    /// Gets or sets the refund amount in the payment order's currency.
    /// Must be positive, greater than zero, and not exceed original payment amount.
    /// Supports partial refunds (amount less than original payment).
    /// Stored in decimal format for precision.
    /// Example: 250.00 for partial refund of ₹250 from ₹500 payment
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Gets or sets the currency code for the refund.
    /// Inherited from parent payment order.
    /// Defaults to "INR" (Indian Rupees).
    /// Must match the currency of the original payment.
    /// Examples: "INR", "USD", "EUR"
    /// </summary>
    public string Currency { get; set; } = "INR";

    /// <summary>
    /// Gets or sets the current status of the refund.
    /// Tracks refund lifecycle: Initiated -> Processed/Failed.
    /// Business rules:
    /// - Initiated: Refund request sent to Razorpay, awaiting processing
    /// - Processed: Refund successfully completed and funds returned to customer
    /// - Failed: Refund processing failed (rare, usually due to Razorpay issues)
    /// Webhook updates status from Initiated to Processed when Razorpay completes refund.
    /// </summary>
    public RefundStatus Status { get; set; }

    /// <summary>
    /// Gets or sets the timestamp when refund was processed by Razorpay.
    /// Recorded when refund status changes to Processed via webhook.
    /// Used for refund reconciliation and reporting.
    /// Nullable. Set only when refund is successfully processed.
    /// </summary>
    public DateTime? ProcessedAt { get; set; }

    /// <summary>
    /// Gets or sets the reason for initiating the refund.
    /// Used for audit trail and customer communication.
    /// Should clearly explain why refund is being processed.
    /// Required field. Examples: "Customer cancellation", "Service not delivered", "Duplicate payment"
    /// </summary>
    public string Reason { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the unique identifier of the admin user who initiated the refund.
    /// Used for audit trail and accountability.
    /// Must be a valid user ID with Admin_User or System_Admin role.
    /// Required field. Tracks who authorized the refund.
    /// </summary>
    public Guid InitiatedBy { get; set; }
    
    /// <summary>
    /// Gets or sets the parent payment order for this refund.
    /// Navigation property for Entity Framework relationship.
    /// Provides access to payment order details including shipment info and original payment amount.
    /// Required for refund validation and event publishing.
    /// </summary>
    public PaymentOrder PaymentOrder { get; set; } = null!;
}

/// <summary>
/// Enumeration representing the possible statuses of a payment refund.
/// Defines the refund lifecycle states and valid transitions.
/// Used for business logic validation and workflow control.
/// </summary>
public enum RefundStatus
{
    /// <summary>
    /// Refund request initiated with Razorpay, awaiting processing.
    /// Initial status when refund is created.
    /// Can transition to Processed or Failed.
    /// Razorpay typically processes refunds within 5-7 business days.
    /// </summary>
    Initiated,

    /// <summary>
    /// Refund successfully processed by Razorpay and funds returned to customer.
    /// Terminal status. Webhook updates status when Razorpay completes refund.
    /// Customer receives funds in their original payment method.
    /// </summary>
    Processed,

    /// <summary>
    /// Refund processing failed.
    /// Rare status, usually due to Razorpay system issues.
    /// Terminal status. Requires manual investigation and retry.
    /// </summary>
    Failed
}

