using Ship24X7.Shared.Domain;

namespace Ship24X7.Payment.Domain.Entities;

/// <summary>
/// Domain entity representing a payment order in the Ship24X7 payment system.
/// Encapsulates payment order data, business rules, and relationships with Razorpay payment gateway.
/// Inherits from BaseEntity for common audit fields (CreatedAt, CreatedBy, UpdatedAt, UpdatedBy, CorrelationId).
/// Tracks payment lifecycle from creation (Pending) through capture (Captured) or failure (Failed) to refund (Refunded).
/// Links shipments to Razorpay orders and payments for payment processing and reconciliation.
/// Supports idempotency to prevent duplicate payment orders for the same request.
/// </summary>
public class PaymentOrder : BaseEntity
{
    /// <summary>
    /// Gets or sets the unique identifier for the payment order.
    /// Primary key in the database.
    /// Used for internal references and API responses.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the unique identifier of the shipment for which payment is being collected.
    /// Foreign key linking payment to shipment in shipment service.
    /// Used to associate payment with specific shipment for fulfillment workflow.
    /// Required field. Must be a valid shipment ID.
    /// </summary>
    public Guid ShipmentId { get; set; }

    /// <summary>
    /// Gets or sets the tracking number of the shipment.
    /// Used in Razorpay receipt for easy identification and reconciliation.
    /// Format: SHIP_{TrackingNumber} in Razorpay order.
    /// Required field. Example: "SHIP123456789"
    /// </summary>
    public string TrackingNumber { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Razorpay order ID generated by Razorpay when order is created.
    /// Unique identifier for the order in Razorpay system.
    /// Used for payment verification and webhook processing.
    /// Required field. Example: "order_ABC123XYZ456"
    /// </summary>
    public string RazorpayOrderId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Razorpay payment ID generated after successful payment.
    /// Unique identifier for the payment transaction in Razorpay system.
    /// Populated after payment verification or webhook notification.
    /// Used for refund operations and payment tracking.
    /// Nullable. Example: "pay_XYZ789ABC123"
    /// </summary>
    public string? RazorpayPaymentId { get; set; }

    /// <summary>
    /// Gets or sets the Razorpay signature for payment verification.
    /// HMAC-SHA256 hash used to validate payment authenticity.
    /// Populated after payment verification.
    /// Ensures payment was actually processed by Razorpay and not tampered with.
    /// Nullable. Example: "a1b2c3d4e5f6..."
    /// </summary>
    public string? RazorpaySignature { get; set; }

    /// <summary>
    /// Gets or sets the payment amount in the specified currency.
    /// Represents the total cost of the shipment including all charges.
    /// Must be positive and greater than zero.
    /// Stored in decimal format for precision.
    /// Example: 500.00 for ₹500
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Gets or sets the currency code for the payment.
    /// Defaults to "INR" (Indian Rupees).
    /// Must be a valid ISO 4217 currency code supported by Razorpay.
    /// Examples: "INR", "USD", "EUR"
    /// </summary>
    public string Currency { get; set; } = "INR";

    /// <summary>
    /// Gets or sets the current status of the payment order.
    /// Tracks payment lifecycle: Pending -> Captured/Failed -> Refunded.
    /// Business rules:
    /// - Pending: Order created, awaiting payment
    /// - Captured: Payment successfully received and verified
    /// - Failed: Payment attempt failed
    /// - Refunded: Payment was captured but later refunded
    /// Only Captured payments can be refunded.
    /// </summary>
    public PaymentStatus Status { get; set; }

    /// <summary>
    /// Gets or sets the timestamp when payment was captured.
    /// Recorded when payment status changes to Captured.
    /// Used for payment reconciliation and reporting.
    /// Nullable. Set only when payment is successfully captured.
    /// </summary>
    public DateTime? CapturedAt { get; set; }

    /// <summary>
    /// Gets or sets the reason for payment failure.
    /// Populated when payment status changes to Failed.
    /// Contains error description from Razorpay for troubleshooting.
    /// Used for customer support and failure analysis.
    /// Nullable. Example: "Card declined", "Insufficient funds"
    /// </summary>
    public string? FailureReason { get; set; }

    /// <summary>
    /// Gets or sets the idempotency key to prevent duplicate payment order creation.
    /// If a payment order with this key already exists, the existing order is returned.
    /// Should be unique per payment request, typically generated by the client.
    /// Ensures duplicate API calls don't create multiple payment orders.
    /// Required field. Example: "ship_123456789_1234567890"
    /// </summary>
    public string IdempotencyKey { get; set; } = string.Empty;
    
    /// <summary>
    /// Gets or sets the collection of refunds associated with this payment order.
    /// Navigation property for Entity Framework relationship.
    /// A payment order can have multiple refunds (partial refunds).
    /// Used to track refund history and calculate total refunded amount.
    /// </summary>
    public ICollection<PaymentRefund> Refunds { get; set; } = new List<PaymentRefund>();
}

/// <summary>
/// Enumeration representing the possible statuses of a payment order.
/// Defines the payment lifecycle states and valid transitions.
/// Used for business logic validation and workflow control.
/// </summary>
public enum PaymentStatus
{
    /// <summary>
    /// Payment order created, awaiting payment from customer.
    /// Initial status when order is created in Razorpay.
    /// Can transition to Captured or Failed.
    /// </summary>
    Pending,

    /// <summary>
    /// Payment successfully received and verified.
    /// Payment signature validated and funds captured.
    /// Can transition to Refunded.
    /// Triggers shipment fulfillment workflow.
    /// </summary>
    Captured,

    /// <summary>
    /// Payment attempt failed.
    /// Customer payment was declined or encountered an error.
    /// Terminal status. Customer needs to retry payment.
    /// </summary>
    Failed,

    /// <summary>
    /// Payment was captured but later refunded to customer.
    /// Full or partial refund processed successfully.
    /// Terminal status. No further transitions.
    /// </summary>
    Refunded
}

